<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="BenchmarkDotNet" Version="0.15.4" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\WaxNBT\WaxNBT.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="..\..\..\.nuget\packages\microsoft.diagnostics.tracing.traceevent\3.1.21\lib\netstandard2.0\Dia2Lib.dll" />
    </ItemGroup>

</Project>
